### ISSUE TITLE
Interrupt

### ISSUE THREAD

**Issue by jvoermans** [jerabaul29/LoggerWavesInIce_InSituWithIridium#21]
@jerabaul29 Is there going to be a conflict somewhere in the software if I use 'attachInterrupt' to measure wind speed?  I'm not an expert on the interrupt function, but it seems it can conflict easily with other processes running on the background...

**Comment by jerabaul29** [comment]
Mmh, I do not think it should, as the interrupt will be on the specific pin you attach to. There are many interrupt handlers routines, so that it is possible to have several interrupts defined at the same time. Would be best to test and check of course, but I would guess this should work :) .

Let me know when you test and how. Maybe you can create a separate project for this feature, and I can take care of putting in the main code? :)
