### ISSUE TITLE
using 32GB card image

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/LoggerWavesInIce_InSituWithIridium#23]
@jvoermans let's discuss here how it goes with using the 32GB card image.

**Comment by jvoermans** [comment]
initially solved. Will do test today...

**Comment by jvoermans** [comment]
You remember when the instrument was deployed in the Antarctic and only GPS messages came through, not the spectra? I first thought the SD card of the RPi was full (which is why I wanted to make sure this time I increased the size). I now actually think the battery is starting to get empty and cannot handle the RPi anymore, draws too much current, and voltage drops to about 3.6V instead of 5.1-5.2V. So, until the RPi is started, everything works fine, but from there on not anymore...

**Comment by jvoermans** [comment]
Including this card ended up with spectrum transmitted through Iridium. So works as expected :)

**Comment by jvoermans** [comment]
Am I missing the 'close' button somewhere? Or are you the only one able to do so? ;)

**Comment by jerabaul29** [comment]
Mmh no you should be able to close too. See the button left to Comment :) .

Great that it works :) .

**Comment by jvoermans** [comment]
That's what I though. I might be crazy...
<img width="1131" alt="Screen Shot 2021-01-23 at 07 49 14" src="https://user-images.githubusercontent.com/43016672/105544998-b1b28b80-5d4f-11eb-86bc-8e4b883ae97c.png">

**Comment by jerabaul29** [comment]
Really weird. I will close then.
